// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Cart struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

type Order struct {
	ID               int64         `json:"id"`
	UserID           int64         `json:"userId"`
	ShippingDetailID sql.NullInt64 `json:"shippingDetailId"`
	Created          time.Time     `json:"created"`
	ExternalOrderID  string        `json:"externalOrderId"`
	PaymentLink      string        `json:"paymentLink"`
	IsPaid           bool          `json:"isPaid"`
	OrderStatus      string        `json:"orderStatus"`
}

type Paper struct {
	ID                int64   `json:"id"`
	Name              string  `json:"name"`
	CostPerSquareInch float64 `json:"costPerSquareInch"`
	Finish            string  `json:"finish"`
}

type Picture struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	UserID int64  `json:"userId"`
}

type Print struct {
	ID         int64         `json:"id"`
	PictureID  int64         `json:"pictureId"`
	PaperID    int64         `json:"paperId"`
	OrderID    sql.NullInt64 `json:"orderId"`
	CartID     sql.NullInt64 `json:"cartId"`
	Width      float64       `json:"width"`
	Height     float64       `json:"height"`
	BorderSize float64       `json:"borderSize"`
	CropX      int64         `json:"cropX"`
	CropY      int64         `json:"cropY"`
	Cost       float64       `json:"cost"`
	Quantity   int64         `json:"quantity"`
}

type ShippingDetail struct {
	ID                int64          `json:"id"`
	ShippingProfileID int64          `json:"shippingProfileId"`
	TrackNumber       sql.NullString `json:"trackNumber"`
}

type ShippingProfile struct {
	ID     int64   `json:"id"`
	Name   string  `json:"name"`
	Cost   float64 `json:"cost"`
	Method string  `json:"method"`
}

type User struct {
	ID       int64     `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
	IsAdmin  bool      `json:"isAdmin"`
	Created  time.Time `json:"created"`
}
